doantotnghiep/routes/web.php
<?php

use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\QuanController;
use App\Http\Controllers\Admin\PhuongController;

use App\Http\Controllers\Admin\Users\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\PagesController;
use App\Http\Controllers\Auth\DangtinController;
use App\Http\Controllers\Auth\CommentController;
use App\Http\Controllers\Auth\SendmailController;
use App\Http\Controllers\Admin\BinhluanController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\LoaiPhongController;

use App\Models\Dangtin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('admin/users/login', [LoginController::class, 'index'])->name('login');
//Route::post('admin/users/login/store', [LoginController::class, 'store']);

//Route::middleware(['auth'])->group(function () {
//
//
//        Route::get('admin/main', [MainController::class, 'index'])->name('admin');
//
//
//        });
//Route::prefix('admin')->group(function () {
//    Route::get('/main', [MainController::class, 'index']);
//    Route::get('/quan',[QuanController::class,'index']);
//    Route::get('/quan/create',[QuanController::class,'create']);
//    Route::get('quan/store',[QuanController::class,'store']);
//    Route::get('/quan/{id}',[QuanController::class,'show']);
//
//    Route::get('/phuong',[HuyenController::class,'index']);
//
//});
//Route::get('admin/login', [AdminController::class, 'index'])->name('login');

//Route::middleware('admin')->group(function (){
//    Route::get('admin/login', [AdminController::class, 'index'])->name('login');
//    Route::post('admin/main', [AdminController::class, 'LoginPost'])->name('admin.dashboard');


Route::get('admin/logout',[AdminController::class,'logout'])->name('admin.logout');


Route::get('admin/login',[AdminController::class,'index'])->name('admin.login');
Route::post('admin/main', [AdminController::class, 'LoginPost'])->name('admin.main');
Route::get('admin/error',[AdminController::class,'error'])->name('admin.error');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin'],'as'=>'admin.'],function (){

    Route::get('main', [MainController::class, 'index']);
    Route::get('/quan',[QuanController::class,'index'])->name('quan');
    Route::get('/quan/create',[QuanController::class,'create'])->name('quan.create');
    Route::post('quan/store',[QuanController::class,'store'])->name('quan.store');
    Route::get('/quan/edit/{quan}',[QuanController::class,'edit'])->name('quan.edit');
    Route::post('quan/update/{quan}',[QuanController::class,'update'])->name('quan.update');
    Route::get('admin/quan/destroy/{id}',[QuanController::class,'destroy'])->name('quan.destroy');

    Route::get('/phuong',[PhuongController::class,'index'])->name('phuong');
    Route::get('/phuong/create',[PhuongController::class,'create'])->name('phuong.create');
    Route::post('phuong/store',[PhuongController::class,'store'])->name('phuong.store');

    Route::get('slide',[\App\Http\Controllers\Admin\SlideController::class,'index'])->name('slide');
    Route::get('/slide/create',[\App\Http\Controllers\Admin\SlideController::class,'create'])->name('slide.create');
    Route::post('slide/store',[\App\Http\Controllers\Admin\SlideController::class,'store'])->name('slide.store');

    Route::get('/dangtin',[\App\Http\Controllers\Admin\DangtinController::class,'index'])->name('dangtin');
    Route::post('duyetbaidang',[\App\Http\Controllers\Admin\DangtinController::class,'duyetbaidang']);
    Route::get('/dangtin/edit/{id}',[\App\Http\Controllers\Admin\DangtinController::class,'edit'])->name('dangtin.edit');
    Route::get('/comment/dangtin/{id}',[\App\Http\Controllers\Admin\DangtinController::class,'destroy'])->name('dangtin.destroy');
    Route::get('/dangtin/search',[DangtinController::class,'searchDangtin']);


    Route::get('taikhoannguoidung',[UserController::class,'index'])->name('taikhoan');
    Route::post('duyettaikhoan',[UserController::class,'duyettaikhoan']);
    Route::get('/taikhoannguoidung/edit/{user}',[UserController::class,'edit'])->name('user.edit');
    Route::post('taikhoannguoidung/update/{user}',[UserController::class,'update'])->name('user.update');
    Route::get('profile',[UserController::class,'profile']);
    Route::post('profile/update/{user}',[UserController::class,'updateprofile'])->name('profile.update');
    Route::get('getupdatepassword',[UserController::class,'getupdatepassword'])->name('password');
    Route::post('postupdatepassword',[UserController::class,'updatepassword'])->name('updatepassword');

    Route::get('loaiphong',[LoaiPhongController::class,'index'])->name('loaiphong');
    Route::get('loaiphong/create',[LoaiPhongController::class,'create'])->name('loaiphong.create');
    Route::post('loaiphong/store',[LoaiPhongController::class,'store'])->name('loaiphong.store');
    Route::post('loaiphong/destroy/{id}',[LoaiPhongController::class,'destroy'])->name('loaiphong.destroy');

    Route::get('/thongke',[\App\Http\Controllers\Admin\ThongkeController::class,'index'])->name('thongke.index');
    Route::get('/thongkenguoidung',[\App\Http\Controllers\Admin\ThongkeController::class,'thongkenguoidung'])->name('thongke.danhsach');
    Route::get('/thongkebieudo',[\App\Http\Controllers\Admin\ThongkeController::class,'thongkebieudo'])->name('thongke.danhsach');

});


//Route::group(['middleware'=>'auth'],function () {

    Route::get('trangchu',[PagesController::class,'trangchu'])->name('trangchu');
    Route::get('dangky',[PagesController::class,'showRegister'])->name('show-register');
    Route::post('dangky',[PagesController::class,'register'])->name('register');
    Route::get('dangnhap',[PagesController::class,'getDangnhap'])->name('show-login');
    Route::post('dangnhap',[PagesController::class,'postDangnhap'])->name('login');
    Route::get('logout',[PagesController::class,'logout'])->name('logout');

    Route::get('dangtin',[DangtinController::class,'index'])->name('dangtin');
    Route::post('dangtin',[DangtinController::class,'create'])->name('create');
    Route::get('trangchitiet/{id}',[DangtinController::class,'trangchitiet'])->name('trangchitiet');
    Route::post('rating',[DangtinController::class,'rating'])->name('rating');

    Route::get('nguoidung',[PagesController::class,'getnguoidung'])->name('nguoidung');
    Route::post('nguoidung/{user}',[PagesController::class,'updatenguoidung'])->name('update');

    Route::get('getupdatepassword',[PagesController::class,'getupdatepassword'])->name('password');
    Route::post('postupdatepassword',[PagesController::class,'updatepassword'])->name('updatepassword');

    Route::get('forgotpassword',[PagesController::class,'showForgotPasswordForm']);
    Route::post('forgotpassword',[PagesController::class,'submitForgotPasswordForm'])->name('forgetPass');
    Route::get('resetpassword/{token}',[PagesController::class,'showResetPasswordForm'])->name('resetpassword');
    Route::post('updateresetpassword',[PagesController::class,'submitResetPasswordForm'])->name('updateresetpassword');


    Route::post('comment/{id}',[CommentController::class,'comment'])->name('comment');


    Route::get('trangchu/loaiphong/{id}',[\App\Http\Controllers\Auth\DanhmucController::class,'index'])->name('trangchu.trochothue');
    Route::get('trangchu/phongtro/{id}',[\App\Http\Controllers\Auth\DanhmucController::class,'quan'])->name('trangchu.phongtro');

    Route::get('dangtin/capnhatdangtin/{id}',[DangtinController::class,'getupdatenguoidung'])->name('capnhat.dangtin');
    Route::post('dangtin/capnhatdangtin/{id}',[DangtinController::class,'updatedangtin'])->name('update.dangtin');



Route::get('send-email',[\App\Http\Controllers\SendMailController::class,'sendmail']);

doantotnghiep/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function setPasswordAttribute($password){
        $this->attributes['password'] = Hash::make($password);
    }
  public function dangtin(){
       return $this->hasMany(Dangtin::class);
  }
  public function danhgia(){
        return $this->belongsTo(Danhgia::class);
  }
  public function permissions(){
        return ['admin.quan','admin.phuong','admin.dangtin'];
  }
  public function hasPermission($route){
     $routes = $this->routes();
     return in_array($route,$routes) ? true : false ;

  }
  public function routes(){
        $data = [];
        foreach ($this->getRoles as $role){
            $permission = json_decode($role->permissions);
            foreach ($permission as $per){
                if (!in_array($per,$data)){
                    array_push($data, $per);
                }
            }
      }
        return $data;
  }
 }

doantotnghiep/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use App\Models\UserRole;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index(){
        $user = User::paginate(2)->fragment('user');
        return view('admin.users.taikhoannguoidung',[
            'title'=>'Quản Lí Tài Khoản'
        ],compact('user'));
    }
    public function duyettaikhoan(Request $request){
        $data = $request->all();
        $user = User::find($data['id']);
        $user->status = $data['status'];
        $user->save();
    }
    public function edit(User $user){
        return view('admin.users.edit',[
            'title'=>'Chỉnh sửa tài khoản'
        ],compact('user'));

    }
    public function update(Request $request,$id){
        $updateuser = User::find($id);
        $updateuser->name = $request->input('name');
        $updateuser->email = $request->input('email');
        $updateuser->password = $request->input('password');
        $updateuser->diachi = $request->input('diachi');
        $updateuser->sdt = $request->input('sdt');
        $updateuser->gioitinh = $request->input('gioitinh');
        $updateuser->ngaysinh = $request->input('ngaysinh');
        $updateuser->role_id = $request->input('role_id');
        if($request->hasFile('Anhdaidien')){
            $destination = public_path('/upload/user').$updateuser->Anhdaidien;
            if (\Illuminate\Support\Facades\File::exists($destination)){
                \Illuminate\Support\Facades\File::delete($destination);
            }
            $file = $request->file('Anhdaidien');
            $destination_path = public_path('/upload/user');
            $file_Name_anhdaidien = time().'_'.$file->getClientOriginalName();
            $file->move($destination_path,$file_Name_anhdaidien);
            $updateuser->Anhdaidien = $file_Name_anhdaidien;
        }
        if($request->hasFile('Anhbia')){
            $destination = public_path('/upload/user').$updateuser->Anhbia;
            if (\Illuminate\Support\Facades\File::exists($destination)){
                \Illuminate\Support\Facades\File::delete($destination);
            }
            $file = $request->file('Anhbia');
            $destination_path = public_path('/upload/user');
            $file_Name_anhbia = time().'_'.$file->getClientOriginalName();
            $file->move($destination_path,$file_Name_anhbia);
            $updateuser->Anhbia = $file_Name_anhbia;
        }
        $updateuser->update();
        return redirect()->back()->with('success','Bạn đã cập nhật thành công');
    }
    public function profile(){
         $user = Auth::user();
        return view('admin.users.profile',[
            'title'=>' Người dùng',
        ],compact('user'))
            ;
    }
    public function updateprofile(Request $request,$id){
        $updateuser = User::find($id);
        $updateuser->name = $request->input('name');
        $updateuser->email = $request->input('email');
        $updateuser->sdt = $request->input('sdt');
        $updateuser->ngaysinh = $request->input('ngaysinh');
        if($request->hasFile('Anhdaidien')){
            $destination = public_path('/upload/user').$updateuser->Anhdaidien;
            if (\Illuminate\Support\Facades\File::exists($destination)){
                \Illuminate\Support\Facades\File::delete($destination);
            }
            $file = $request->file('Anhdaidien');
            $destination_path = public_path('/upload/user');
            $file_Name_anhdaidien = time().'_'.$file->getClientOriginalName();
            $file->move($destination_path,$file_Name_anhdaidien);
            $updateuser->Anhdaidien = $file_Name_anhdaidien;
        }
        if($request->hasFile('Anhbia')){
            $destination = public_path('/upload/user').$updateuser->Anhbia;
            if (\Illuminate\Support\Facades\File::exists($destination)){
                \Illuminate\Support\Facades\File::delete($destination);
            }
            $file = $request->file('Anhbia');
            $destination_path = public_path('/upload/user');
            $file_Name_anhbia = time().'_'.$file->getClientOriginalName();
            $file->move($destination_path,$file_Name_anhbia);
            $updateuser->Anhbia = $file_Name_anhbia;
        }
        $updateuser->update();
        return redirect()->back()->with('success','Bạn đã cập nhật thành công');
    }
    public function getupdatepassword(){
        return view('admin.users.doipassword',[
            'title'=>'Thay đổi password',
        ]);
    }

    public function updatepassword(Request $request){
        if (!(Hash::check($request->get('current-password'), Auth::user()->password))) {
            // The passwords matches
            return redirect()->back()->with("error","Mật khẩu hiện tại của bạn không đúng");
        }

        if(strcmp($request->get('current-password'), $request->get('new-password')) == 0){
            // Current password and new password same
            return redirect()->back()->with("error","Mật khẩu mới trùng với mật khẩu cũ của bạn");
        }

        $request->validate([
            'current-password' => 'required',
            'new-password' => 'required|string|min:8|confirmed',
        ]);

        //Change Password
        $user = Auth::user();
        $user->password =($request->get('new-password'));
        $user->save();

        return redirect()->back()->with("success","Thay đổi password thành công!!");
    }
}

doantotnghiep/app/Http/Controllers/Admin/Users/LoginController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class LoginController extends Controller
{
    public function index()
    {
        return view('admin.users.login', [
            'title' => 'Đăng Nhập Hệ Thống'
        ]);
    }

    public function store(Request $request)
    {
        var_dump($request->email);
        exit;
    }
}

doantotnghiep/resources/views/admin/users/doipassword.blade.php
@extends('admin.main')
@section( 'content')
    <div class="container">
        <div class="row">

            <div class="col-md-10 offset-2">
                <div class="panel panel-default">
                    <h2>Thay đổi mật khẩu</h2>

                    <div class="panel-body">
                        @if (session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if($errors)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">{{ $error }}</div>
                            @endforeach
                        @endif
                        <form class="form-horizontal" method="POST" action="{{ route('admin.updatepassword') }}">
                            @csrf

                            <div class="form-group{{ $errors->has('current-password') ? ' has-error' : '' }}">
                                <label for="new-password" class="col-md-4 control-label">Mật khẩu hiện tại</label>

                                <div class="col-md-6">
                                    <input id="current-password" type="password" class="form-control" name="current-password" required>

                                    @if ($errors->has('current-password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('current-password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('new-password') ? ' has-error' : '' }}">
                                <label for="new-password" class="col-md-4 control-label">Mật khẩu mới</label>

                                <div class="col-md-6">
                                    <input id="new-password" type="password" class="form-control" name="new-password" required>

                                    @if ($errors->has('new-password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('new-password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="new-password-confirm" class="col-md-4 control-label">Nhập lại password</label>

                                <div class="col-md-6">
                                    <input id="new-password-confirm" type="password" class="form-control" name="new-password_confirmation" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Thay đổi Password
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

doantotnghiep/resources/views/admin/users/edit.blade.php
@extends('admin.main')
@section( 'content')
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="../../../adminlte/plugins/fontawesome-free/css/all.min.css">
        <!-- icheck bootstrap -->
        <link rel="stylesheet" href="../../../adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="../../../adminlte/dist/css/adminlte.min.css">
    </head>

    <div class="container">

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


            @if (Session::has('error'))
                <div class="alert alert-danger">
                    {{ Session::get('error') }}
                </div>
            @endif


            @if (Session::has('success'))
                <div class="alert alert-success">
                    {{ Session::get('success') }}
                </div>
            @endif
            <form action="{{route('admin.user.update',$user->id)}}" method="post">
                @csrf
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" name="name" value="{{$user->name}}">
                            </div>
                            <div class="form-group">
                                <label>Địa chỉ</label>
                                <input type="text" class="form-control" name="diachi" value="{{$user->diachi}}">
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="text" class="form-control" name="email" value="{{$user->email}}">
                            </div>
                            <div class="form-group">
                                <label>Sdt</label>
                                <input type="text" class="form-control" name="sdt" value="{{$user->sdt}}">
                            </div>
                            <div class="form-group">
                                <label>Giới tính</label>
                                <input type="text" class="form-control" name="gioitinh" value="{{$user->gioitinh}}">
                            </div>
                            <div class="form-group">
                                <label>Ngày sinh</label>
                                <input type="date" class="form-control" name="ngaysinh" value="{{$user->ngaysinh}}">
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    <img src="/upload/user/{{$user->Anhdaidien}}" width="120">
                                    <input name="Anhbia" value="{{$user->Anhdaidien}}" type="file" class="form-control">
                                    <label>Ảnh bìa</label>
                                </div>

                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    <img src="/upload/user/{{$user->Anhbia}}" width="120">
                                    <input name="Anhbia" value="{{$user->Anhbia}}" type="file" class="form-control">
                                    <label>Ảnh bìa</label>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input value="{{$user->role_id}}">
                            </div>
                        </div>
                        <button type="submit">Lưu</button>


                    </div>
                </div>
            </form>

        </div>
    </div>
    </div>
@endsection

doantotnghiep/resources/views/admin/users/profile.blade.php
@extends('admin.main')
@section( 'content')
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="/upload/user/{{$user->Anhdaidien}}" style="width: 300px;height: 300px; border-radius: 50% ">
            </div>

                <div class="col-md-8">
                    <div class="container">
                        <form action="{{route('admin.profile.update',$user->id)}}" method="post">
                            @csrf
                        <div class="row">

                            <div class="col-md-6 mt-5">
                                <div class="form-group">
                                    <label>Tên Tài Khoản</label>
                                    <input type="text" name="name" class="form-group" value="{{$user->name}}" >
                                </div>
                                <div class="form-group">
                                    <label>Ngày sinh</label>
                                    <input type="text" name="ngaysinh" class="form-group" value="{{$user->ngaysinh}}" >
                                </div>
                            </div>
                            <div class="col-md-6 mt-5">
                                <div class="form-group">
                                    <label>Số điện thoại</label>
                                    <input type="text" name="sdt" class="form-group" value="{{$user->sdt}}" >
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="text" name="email" class="form-group" value="{{$user->email}}" >
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="file" name="Anhdaidien">
                            </div>
                        </div>
                            <button class="btn-primary" type="submit">Save</button>
                        </form>
                        <a href="{{url('http://localhost:8000/admin/getupdatepassword')}}">Đổi mật khẩu </a>

                    </div>
                </div>



        </div>

    </div>
@endsection

doantotnghiep/resources/views/admin/users/taikhoannguoidung.blade.php
@extends('admin.main')
@section( 'content')
    <div class="container">
        <div class="row" style="margin-bottom: 20px;">
            <div class="col-lg-12 margin-tb">
                <div id="notify_dangtin"></div>
                <div class="pull-right" style="margin-top: 20px;">
                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if(session('thongbao'))
            <span class="alert alert-success">
                                    <strong>{{session('thongbao')}}</strong>
                                </span>

        @endif
        @if(session('baoloi'))
            <span class="alert alert-danger">
                <strong>{{session('baoloi')}}</strong>
            </span>

        @endif
        <table class="table table-bordered">
            <tr>
                <th>Duyệt</th>
                <th>Hoạt động</th>
                <th>Tên tài khoản</th>
                <th>Email</th>
                <th>Địa chỉ</th>
                <th>Số điện thoại</th>
                <th>Giới tính</th>
                <th>Ảnh đại diện</th>
                <th>Ảnh bìa</th>
            </tr>
            @foreach ($user as $data)
                @if($data->role_id == 2)
                <tr>
                    <td>
                        @if($data->status == 1 )
                            <input type="button" data-status="0" id="{{$data->id}}" class="btn btn-secondary duyet_btn" value="Mở khóa">
                        @else
                            <input type="button" data-status="1" id="{{$data->id}}" class="btn btn-primary duyet_btn" value="Khóa tài khoản">
                        @endif
                    </td>
                    <td>
                        <a href="" class="btn btn-xs btn-warning">Roles</a>
                        <a href="{{route('admin.user.edit',$data->id)}}" class="btn btn-xs btn-primary">Sửa</a>
                        <a href="" class="btn btn-xs btn-danger">Xóa</a>
                    </td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->email}}</td>
                    <td>{{$data->diachi}}</td>
                    <td>{{$data->sdt}}</td>
                    <td>{{$data->gioitinh}}</td>
                    <td><img  src="/upload/user/{{ $data->Anhdaidien }}" width="120" alt=""></td>
                    <td><img  src="/upload/user/{{ $data->Anhbia}}" width="120" alt=""></td>

                </tr>
                @else
                @endif
            @endforeach
        </table>

        <nav aria-label="Page navigation ">
            <nav aria-label="Page navigation example">
                </li>
                {{$user->links()}}
                </ul>

            </nav></nav>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $('.duyet_btn').click(function (){
            var status = $(this).data('status');
            var id = $(this).attr('id');
            if(status == 0){
                var alert = 'Bạn đã mở tài khoản';
            }
            else {
                var alert = 'Bạn đã khóa tài khoản'
            }

            $.ajax({
                url:"{{url('admin/duyettaikhoan')}}",
                method:"POST",
                headers:{
                    'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
                },

                data:{status:status,id:id},
                success:function(data) {
                    $('#notify_dangtin').html(data);
                    $('#notify_dangtin').html('<span class="text text-alert">'+alert+'</span>');
                }





            })
        })

    </script>
@endsection