doantotnghiep/routes/web.php
<?php

use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\QuanController;
use App\Http\Controllers\Admin\PhuongController;

use App\Http\Controllers\Admin\Users\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\PagesController;
use App\Http\Controllers\Auth\DangtinController;
use App\Http\Controllers\Auth\CommentController;
use App\Http\Controllers\Auth\SendmailController;
use App\Http\Controllers\Admin\BinhluanController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\LoaiPhongController;

use App\Models\Dangtin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('admin/users/login', [LoginController::class, 'index'])->name('login');
//Route::post('admin/users/login/store', [LoginController::class, 'store']);

//Route::middleware(['auth'])->group(function () {
//
//
//        Route::get('admin/main', [MainController::class, 'index'])->name('admin');
//
//
//        });
//Route::prefix('admin')->group(function () {
//    Route::get('/main', [MainController::class, 'index']);
//    Route::get('/quan',[QuanController::class,'index']);
//    Route::get('/quan/create',[QuanController::class,'create']);
//    Route::get('quan/store',[QuanController::class,'store']);
//    Route::get('/quan/{id}',[QuanController::class,'show']);
//
//    Route::get('/phuong',[HuyenController::class,'index']);
//
//});
//Route::get('admin/login', [AdminController::class, 'index'])->name('login');

//Route::middleware('admin')->group(function (){
//    Route::get('admin/login', [AdminController::class, 'index'])->name('login');
//    Route::post('admin/main', [AdminController::class, 'LoginPost'])->name('admin.dashboard');


Route::get('admin/logout',[AdminController::class,'logout'])->name('admin.logout');


Route::get('admin/login',[AdminController::class,'index'])->name('admin.login');
Route::post('admin/main', [AdminController::class, 'LoginPost'])->name('admin.main');
Route::get('admin/error',[AdminController::class,'error'])->name('admin.error');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin'],'as'=>'admin.'],function (){

    Route::get('main', [MainController::class, 'index']);
    Route::get('/quan',[QuanController::class,'index'])->name('quan');
    Route::get('/quan/create',[QuanController::class,'create'])->name('quan.create');
    Route::post('quan/store',[QuanController::class,'store'])->name('quan.store');
    Route::get('/quan/edit/{quan}',[QuanController::class,'edit'])->name('quan.edit');
    Route::post('quan/update/{quan}',[QuanController::class,'update'])->name('quan.update');
    Route::get('admin/quan/destroy/{id}',[QuanController::class,'destroy'])->name('quan.destroy');

    Route::get('/phuong',[PhuongController::class,'index'])->name('phuong');
    Route::get('/phuong/create',[PhuongController::class,'create'])->name('phuong.create');
    Route::post('phuong/store',[PhuongController::class,'store'])->name('phuong.store');

    Route::get('slide',[\App\Http\Controllers\Admin\SlideController::class,'index'])->name('slide');
    Route::get('/slide/create',[\App\Http\Controllers\Admin\SlideController::class,'create'])->name('slide.create');
    Route::post('slide/store',[\App\Http\Controllers\Admin\SlideController::class,'store'])->name('slide.store');

    Route::get('/dangtin',[\App\Http\Controllers\Admin\DangtinController::class,'index'])->name('dangtin');
    Route::post('duyetbaidang',[\App\Http\Controllers\Admin\DangtinController::class,'duyetbaidang']);
    Route::get('/dangtin/edit/{id}',[\App\Http\Controllers\Admin\DangtinController::class,'edit'])->name('dangtin.edit');
    Route::get('/comment/dangtin/{id}',[\App\Http\Controllers\Admin\DangtinController::class,'destroy'])->name('dangtin.destroy');
    Route::get('/dangtin/search',[DangtinController::class,'searchDangtin']);


    Route::get('taikhoannguoidung',[UserController::class,'index'])->name('taikhoan');
    Route::post('duyettaikhoan',[UserController::class,'duyettaikhoan']);
    Route::get('/taikhoannguoidung/edit/{user}',[UserController::class,'edit'])->name('user.edit');
    Route::post('taikhoannguoidung/update/{user}',[UserController::class,'update'])->name('user.update');
    Route::get('profile',[UserController::class,'profile']);
    Route::post('profile/update/{user}',[UserController::class,'updateprofile'])->name('profile.update');
    Route::get('getupdatepassword',[UserController::class,'getupdatepassword'])->name('password');
    Route::post('postupdatepassword',[UserController::class,'updatepassword'])->name('updatepassword');

    Route::get('loaiphong',[LoaiPhongController::class,'index'])->name('loaiphong');
    Route::get('loaiphong/create',[LoaiPhongController::class,'create'])->name('loaiphong.create');
    Route::post('loaiphong/store',[LoaiPhongController::class,'store'])->name('loaiphong.store');
    Route::post('loaiphong/destroy/{id}',[LoaiPhongController::class,'destroy'])->name('loaiphong.destroy');

    Route::get('/thongke',[\App\Http\Controllers\Admin\ThongkeController::class,'index'])->name('thongke.index');
    Route::get('/thongkenguoidung',[\App\Http\Controllers\Admin\ThongkeController::class,'thongkenguoidung'])->name('thongke.danhsach');
    Route::get('/thongkebieudo',[\App\Http\Controllers\Admin\ThongkeController::class,'thongkebieudo'])->name('thongke.danhsach');

});


//Route::group(['middleware'=>'auth'],function () {

    Route::get('trangchu',[PagesController::class,'trangchu'])->name('trangchu');
    Route::get('dangky',[PagesController::class,'showRegister'])->name('show-register');
    Route::post('dangky',[PagesController::class,'register'])->name('register');
    Route::get('dangnhap',[PagesController::class,'getDangnhap'])->name('show-login');
    Route::post('dangnhap',[PagesController::class,'postDangnhap'])->name('login');
    Route::get('logout',[PagesController::class,'logout'])->name('logout');

    Route::get('dangtin',[DangtinController::class,'index'])->name('dangtin');
    Route::post('dangtin',[DangtinController::class,'create'])->name('create');
    Route::get('trangchitiet/{id}',[DangtinController::class,'trangchitiet'])->name('trangchitiet');
    Route::post('rating',[DangtinController::class,'rating'])->name('rating');

    Route::get('nguoidung',[PagesController::class,'getnguoidung'])->name('nguoidung');
    Route::post('nguoidung/{user}',[PagesController::class,'updatenguoidung'])->name('update');

    Route::get('getupdatepassword',[PagesController::class,'getupdatepassword'])->name('password');
    Route::post('postupdatepassword',[PagesController::class,'updatepassword'])->name('updatepassword');

    Route::get('forgotpassword',[PagesController::class,'showForgotPasswordForm']);
    Route::post('forgotpassword',[PagesController::class,'submitForgotPasswordForm'])->name('forgetPass');
    Route::get('resetpassword/{token}',[PagesController::class,'showResetPasswordForm'])->name('resetpassword');
    Route::post('updateresetpassword',[PagesController::class,'submitResetPasswordForm'])->name('updateresetpassword');


    Route::post('comment/{id}',[CommentController::class,'comment'])->name('comment');


    Route::get('trangchu/loaiphong/{id}',[\App\Http\Controllers\Auth\DanhmucController::class,'index'])->name('trangchu.trochothue');
    Route::get('trangchu/phongtro/{id}',[\App\Http\Controllers\Auth\DanhmucController::class,'quan'])->name('trangchu.phongtro');

    Route::get('dangtin/capnhatdangtin/{id}',[DangtinController::class,'getupdatenguoidung'])->name('capnhat.dangtin');
    Route::post('dangtin/capnhatdangtin/{id}',[DangtinController::class,'updatedangtin'])->name('update.dangtin');



Route::get('send-email',[\App\Http\Controllers\SendMailController::class,'sendmail']);

doantotnghiep/app/Models/Dangtin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dangtin extends Model
{
    use HasFactory;
    protected $table= "dangtins";
    protected $fillable=[
        'Tieude',
        'Diachi',
        'Giaphong',
        'Dientich',
        'Sdt',
        'Mota',
        'Hinhanh',
        'tiennghi',
        'soluongphong',
        'loaiphong_id',
        'phuong_id',
        'user_id',
        'status'
    ];
    public function phuong()
    {
        return $this->belongsTo(Phuong::class);
    }
    public function loaiphong(){
        return $this->belongsTo(Loaiphong::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function comment(){
        return $this->hasMany(Comment::class);
    }
    public function like(){
        return $this->hasMany(Like::class,'dangtin_id')->sum('like');
    }
    public function danhgia(){
        return $this->hasMany(Danhgia::class);
    }
    public function scopeSearch($query){
        if ($key = request()->key){
            $query = $query->where('Tieude','like','%'.$key.'%');
        }
        return $query;
    }
}

doantotnghiep/app/Http/Controllers/Admin/DangtinController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Dangtin;
use App\Models\Danhgia;
use App\Models\User;
use Illuminate\Http\Request;
use PHPUnit\Framework\Constraint\Count;

class DangtinController extends Controller
{
    public function index()
    {
        $dangtin = Dangtin::orderBy('created_at','DESC')->search()->paginate(3);
        return view('admin.dangtin.dangtin', [
            'title' => 'Quản lí Đăng tin'
        ], compact('dangtin'));
    }

    public function duyetbaidang(Request $request)
    {
        $data = $request->all();
        $dangtin = Dangtin::find($data['id']);
        $dangtin->status = $data['status'];
        $dangtin->save();
    }

    public function edit($id)
    {
        $dangtin = Dangtin::find($id);
        $comment = Comment::where('dangtin_id',$id)->count('id');
        $danhgia = Danhgia::count();
        $grate = Danhgia::where('dangtin_id',$id)->avg('grate');
        $grate = round($grate);
        return view('admin.dangtin.xemdangtin', [
                'title' => 'Xem bài đăng'
            ]
            , compact('dangtin', 'comment', 'danhgia','grate'));
    }

    public function destroy($id)
    {
        $comment = Comment::find($id);
        $comment->delete();
        return redirect()->route('admin.dangtin')->with('thongbao','Xóa thành công');

    }
    public function search(Request $request){
        $output = '';
        $dangtin = Dangtin::where('Tieude','LIKE','%'.$request->keyword.'%')->get();
        foreach ($dangtin as $dangtin){
            $output = '<tr>
                     <td>'.$dangtin->Tieude.'</td>
                    <td>'.$dangtin->Diachi.'</td>
                    <td>'.$dangtin->Giaphong.'</td>
                    <td>'.$dangtin->user->name.'</td>
                       </tr>';
        }
        return response()->json($output);

    }
}

doantotnghiep/resources/views/admin/dangtin/dangtin.blade.php
@extends('admin.main')
@section( 'content')
    <div class="container">
        <div class="row" style="margin-bottom: 20px;">
            <div class="col-lg-12 margin-tb">
                <div id="notify_dangtin"></div>
                <div class="pull-right" style="margin-top: 20px;">
                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if(session('thongbao'))
            <span class="alert alert-success">
                                    <strong>{{session('thongbao')}}</strong>
                                </span>

        @endif
        @if(session('baoloi'))
            <span class="alert alert-danger">
                <strong>{{session('baoloi')}}</strong>
            </span>

        @endif
        <form action="" class="form-inline">
            <div class="form-group">
                <input class="form-control" name="key" placeholder="Tìm kiếm.."/>
            </div>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-search"></i>
            </button>
        </form>



        <table class="table table-bordered mt-5">
            <tr>
                <th>Duyệt
                <th>Tiêu đề</th>
                <th>Địa chỉ</th>
                <th>Giá</th>
                <th>Người đăng</th>
                <th>Ảnh</th>
                <th>Diện tích</th>
                <th>Số lượng phòng</th>
                <th>Ngày đăng</th>
                <th>Tình trạng</th>
                <th>Hành động</th>
            </tr>
            @foreach ($dangtin as $data)
                <tr>

                    <td>
                        @if($data->status == 1 )
                            <input type="button" data-status="0" id="{{$data->id}}" class="btn btn-danger duyet_btn" value="Bỏ duyệt">
                        @else
                            <input type="button" data-status="1" id="{{$data->id}}" class="btn btn-success duyet_btn" value="Duyệt">
                        @endif
                    </td>
                    <td>{{ $data->Tieude }}</td>
                    <td>{{$data->Diachi}}</td>
                    <td>{{($data->Giaphong)}}vnđ</td>
                    <td>{{$data->user->name}}</td>
                    <td><img src="/upload/dangtin/{{$data->Hinhanh}}" width="120"></td>
                    <td>{{$data->Dientich}}m<sup>2</sup></td>
                    <td>{{$data->soluongphong}}</td>
                    <td>{{$data->created_at}}</td>
                    <td>
                       @if($data->status == 0)
                          <span style="color: red">Chưa duyệt</span>
                        @else
                           <span style="color: #0c84ff">Đã duyệt</span>

                        @endif
                    </td>
                    <td>
                        <a class="btn btn-sm" href="{{route('admin.dangtin.edit',$data->id)}}">
                            <i class="fas fa-edit">Xem</i>
                        </a>
                    @csrf
                </tr>
            @endforeach
        </table>

        <nav aria-label="Page navigation ">
            <nav aria-label="Page navigation example">
                {{ $dangtin->appends(request()->all())->links()}}
                </li>
                </ul>

            </nav></nav>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $('.duyet_btn').click(function (){
            var status = $(this).data('status');
            var id = $(this).attr('id');
            if(status == 0){
                var alert = 'Bạn đã bỏ duyệt ';
            }
            else {
                var alert = 'Bạn đã duyệt bài đăng'
            }

            $.ajax({
                url:"{{url('admin/duyetbaidang')}}",
                method:"POST",
                headers:{
                    'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
                },

               data:{status:status,id:id},
                success:function(data) {
                    $('#notify_dangtin').html(data);
                    $('#notify_dangtin').html('<span class="alert alert-default-primary">'+alert+'</span>');
                }
            })
        })
    </script>
@endsection
@section('js')
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdn.baotrongit.com/Money-Format-Plugin/money_format.js"></script>
    <script type="text/javascript">
        $('.money').simpleMoneyFormat();
    </script>
@endsection

doantotnghiep/resources/views/admin/dangtin/xemdangtin.blade.php
@extends('admin.main')
@section( 'content')
    <html>
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="../../../adminlte/plugins/fontawesome-free/css/all.min.css">
        <!-- icheck bootstrap -->
        <link rel="stylesheet" href="../../../adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="../../../adminlte/dist/css/adminlte.min.css">
    </head>
    <body>
    <div class="container">
              <div class="card-body">
            <form action="#" method="post">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group">
                                <strong>Bài Đăng: </strong>
                                <span>{{$dangtin->Tieude}}</span>
                            </div>
                        </div>
                        <hr>
                        <div class="col-md-12">
                            <div class="form-group">
                                <strong>Địa chỉ :</strong>
                                <span>{{$dangtin->Diachi}}</span>
                            </div>
                        </div>
                        <hr>
                        <div class="col-md-12">
                            <div class="form-group">
                                <strong>Giá phòng:</strong>
                                <span>{{$dangtin->Giaphong}}vnđ</span>
                            </div>
                        </div>
                        <hr>
                        <div class="col-md-12">
                            <div class="form-group">
                                <strong>Diện tích:</strong>
                                <span>{{$dangtin->Dientich}}</span>m<sup>2</sup>
                            </div>
                        </div>
                        <hr>
                        <div class="col-md-12">
                            <div class="form-group">
                                <strong>Hình ảnh:</strong>
                                <br>
                                <img src="/upload/dangtin/{{$dangtin->Hinhanh}}" style="width: 300px" >
                            </div>
                        </div>
                        <hr>
                        <div class="col-md-12">
                            <div class="form-group">
                                <strong>Mô tả:</strong>
                                <span>{{$dangtin->Mota}}</span>
                            </div>
                        </div>
                        <hr>

                    </div>
                    <div class="col-md-6">

                            <div class="form-group">
                                <strong>Người đăng:</strong>
                                <span style="color: red">{{$dangtin->user->name }}</span>
                            </div>
                        <hr>
                        <div class="form-group">
                            <strong>Loại Hình:</strong>
                            <span>{{$dangtin->loaiphong->Tenloaiphong }}</span>
                        </div>
                        <hr>
                        <div class="form-group">
                            <strong>Số điện thoại:</strong>
                            <span style="color: #074f07;">{{$dangtin->Sdt}}</span>
                        </div>
                        <hr>
                        <div class="form-group">
                            <strong>Loại Hình :</strong>
                            <span style="color: #00bb00">{{$dangtin->loaiphong->Tenloaiphong }}</span>
                        </div>
                        <hr>
                        <div class="form-group">
                            <strong>Số bình luận :</strong>
                            <span>{{$comment}}</span>
                        </div>
                        <hr>
                        <div class="form-group">
                            <strong>Điểm đánh giá:</strong>
                            <span>{{$grate}}</span><i class="fa fa-star" style="color: yellow"></i>
                        </div>
                    </div>
                </div>

            </form>
                  <hr>
                  <div class="container">
                      <div class="row">
                          <div  class="col-md-6">

                              <h3>Danh sách bình luận</h3>
                              @foreach($dangtin->comment as $data)
                                  <div class="mt-2">

                                      <div class="d-flex flex-row p-3">

                                          <img src="/upload/user/{{$data->user->Anhdaidien}}" width="40" height="40" class="rounded-circle mr-3">

                                          <div class="w-100">

                                              <div class="d-flex justify-content-between align-items-center">
                                                  <div class="d-flex flex-row align-items-center">
                                                      <span class="mr-2"></span>
                                                      <small class="c-badge" style="width:180px;font-size: 18px">{{$data->user->name}}</small>
                                                  </div>
                                                  <small>{{$data->created_at}}</small>
                                              </div>

                                              <p class="text-justify comment-text mb-0" style="color: #0a0e14;font-size: 16px">{{$data->noidung}}</p>

                                              <div class="d-flex flex-row user-feed">

                                                  <span class="wish"><i class="fa fa-heartbeat mr-2"></i>{{$data->dangtin->Tieude}}</span>

                                                  <span class="ml-3"><a href="{{route('admin.dangtin.destroy',$data->id)}}" type="submit"  class="fa fa-comments-o mr-2" id="btn-reply">Xóa</a></span>


                                              </div>

                                          </div>


                                      </div>
                                  </div>
                              @endforeach
                          </div>


                      </div>
                  </div>

                  <div class="pull-right" style="margin-top: 20px;">
                <a class="btn btn-success" href="{{url('http://localhost:8000/admin/dangtin')}}">Quay lại
                </a>
            </div>
        </div>
    </div>
    </body>
    </html>
@endsection