doantotnghiep/routes/web.php
<?php

use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\QuanController;
use App\Http\Controllers\Admin\PhuongController;

use App\Http\Controllers\Admin\Users\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\PagesController;
use App\Http\Controllers\Auth\DangtinController;
use App\Http\Controllers\Auth\CommentController;
use App\Http\Controllers\Auth\SendmailController;
use App\Http\Controllers\Admin\BinhluanController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\LoaiPhongController;

use App\Models\Dangtin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('admin/users/login', [LoginController::class, 'index'])->name('login');
//Route::post('admin/users/login/store', [LoginController::class, 'store']);

//Route::middleware(['auth'])->group(function () {
//
//
//        Route::get('admin/main', [MainController::class, 'index'])->name('admin');
//
//
//        });
//Route::prefix('admin')->group(function () {
//    Route::get('/main', [MainController::class, 'index']);
//    Route::get('/quan',[QuanController::class,'index']);
//    Route::get('/quan/create',[QuanController::class,'create']);
//    Route::get('quan/store',[QuanController::class,'store']);
//    Route::get('/quan/{id}',[QuanController::class,'show']);
//
//    Route::get('/phuong',[HuyenController::class,'index']);
//
//});
//Route::get('admin/login', [AdminController::class, 'index'])->name('login');

//Route::middleware('admin')->group(function (){
//    Route::get('admin/login', [AdminController::class, 'index'])->name('login');
//    Route::post('admin/main', [AdminController::class, 'LoginPost'])->name('admin.dashboard');


Route::get('admin/logout',[AdminController::class,'logout'])->name('admin.logout');


Route::get('admin/login',[AdminController::class,'index'])->name('admin.login');
Route::post('admin/main', [AdminController::class, 'LoginPost'])->name('admin.main');
Route::get('admin/error',[AdminController::class,'error'])->name('admin.error');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin'],'as'=>'admin.'],function (){

    Route::get('main', [MainController::class, 'index']);
    Route::get('/quan',[QuanController::class,'index'])->name('quan');
    Route::get('/quan/create',[QuanController::class,'create'])->name('quan.create');
    Route::post('quan/store',[QuanController::class,'store'])->name('quan.store');
    Route::get('/quan/edit/{quan}',[QuanController::class,'edit'])->name('quan.edit');
    Route::post('quan/update/{quan}',[QuanController::class,'update'])->name('quan.update');
    Route::get('admin/quan/destroy/{id}',[QuanController::class,'destroy'])->name('quan.destroy');

    Route::get('/phuong',[PhuongController::class,'index'])->name('phuong');
    Route::get('/phuong/create',[PhuongController::class,'create'])->name('phuong.create');
    Route::post('phuong/store',[PhuongController::class,'store'])->name('phuong.store');

    Route::get('slide',[\App\Http\Controllers\Admin\SlideController::class,'index'])->name('slide');
    Route::get('/slide/create',[\App\Http\Controllers\Admin\SlideController::class,'create'])->name('slide.create');
    Route::post('slide/store',[\App\Http\Controllers\Admin\SlideController::class,'store'])->name('slide.store');

    Route::get('/dangtin',[\App\Http\Controllers\Admin\DangtinController::class,'index'])->name('dangtin');
    Route::post('duyetbaidang',[\App\Http\Controllers\Admin\DangtinController::class,'duyetbaidang']);
    Route::get('/dangtin/edit/{id}',[\App\Http\Controllers\Admin\DangtinController::class,'edit'])->name('dangtin.edit');
    Route::get('/comment/dangtin/{id}',[\App\Http\Controllers\Admin\DangtinController::class,'destroy'])->name('dangtin.destroy');
    Route::get('/dangtin/search',[DangtinController::class,'searchDangtin']);


    Route::get('taikhoannguoidung',[UserController::class,'index'])->name('taikhoan');
    Route::post('duyettaikhoan',[UserController::class,'duyettaikhoan']);
    Route::get('/taikhoannguoidung/edit/{user}',[UserController::class,'edit'])->name('user.edit');
    Route::post('taikhoannguoidung/update/{user}',[UserController::class,'update'])->name('user.update');
    Route::get('profile',[UserController::class,'profile']);
    Route::post('profile/update/{user}',[UserController::class,'updateprofile'])->name('profile.update');
    Route::get('getupdatepassword',[UserController::class,'getupdatepassword'])->name('password');
    Route::post('postupdatepassword',[UserController::class,'updatepassword'])->name('updatepassword');

    Route::get('loaiphong',[LoaiPhongController::class,'index'])->name('loaiphong');
    Route::get('loaiphong/create',[LoaiPhongController::class,'create'])->name('loaiphong.create');
    Route::post('loaiphong/store',[LoaiPhongController::class,'store'])->name('loaiphong.store');
    Route::post('loaiphong/destroy/{id}',[LoaiPhongController::class,'destroy'])->name('loaiphong.destroy');

    Route::get('/thongke',[\App\Http\Controllers\Admin\ThongkeController::class,'index'])->name('thongke.index');
    Route::get('/thongkenguoidung',[\App\Http\Controllers\Admin\ThongkeController::class,'thongkenguoidung'])->name('thongke.danhsach');
    Route::get('/thongkebieudo',[\App\Http\Controllers\Admin\ThongkeController::class,'thongkebieudo'])->name('thongke.danhsach');

});


//Route::group(['middleware'=>'auth'],function () {

    Route::get('trangchu',[PagesController::class,'trangchu'])->name('trangchu');
    Route::get('dangky',[PagesController::class,'showRegister'])->name('show-register');
    Route::post('dangky',[PagesController::class,'register'])->name('register');
    Route::get('dangnhap',[PagesController::class,'getDangnhap'])->name('show-login');
    Route::post('dangnhap',[PagesController::class,'postDangnhap'])->name('login');
    Route::get('logout',[PagesController::class,'logout'])->name('logout');

    Route::get('dangtin',[DangtinController::class,'index'])->name('dangtin');
    Route::post('dangtin',[DangtinController::class,'create'])->name('create');
    Route::get('trangchitiet/{id}',[DangtinController::class,'trangchitiet'])->name('trangchitiet');
    Route::post('rating',[DangtinController::class,'rating'])->name('rating');

    Route::get('nguoidung',[PagesController::class,'getnguoidung'])->name('nguoidung');
    Route::post('nguoidung/{user}',[PagesController::class,'updatenguoidung'])->name('update');

    Route::get('getupdatepassword',[PagesController::class,'getupdatepassword'])->name('password');
    Route::post('postupdatepassword',[PagesController::class,'updatepassword'])->name('updatepassword');

    Route::get('forgotpassword',[PagesController::class,'showForgotPasswordForm']);
    Route::post('forgotpassword',[PagesController::class,'submitForgotPasswordForm'])->name('forgetPass');
    Route::get('resetpassword/{token}',[PagesController::class,'showResetPasswordForm'])->name('resetpassword');
    Route::post('updateresetpassword',[PagesController::class,'submitResetPasswordForm'])->name('updateresetpassword');


    Route::post('comment/{id}',[CommentController::class,'comment'])->name('comment');


    Route::get('trangchu/loaiphong/{id}',[\App\Http\Controllers\Auth\DanhmucController::class,'index'])->name('trangchu.trochothue');
    Route::get('trangchu/phongtro/{id}',[\App\Http\Controllers\Auth\DanhmucController::class,'quan'])->name('trangchu.phongtro');

    Route::get('dangtin/capnhatdangtin/{id}',[DangtinController::class,'getupdatenguoidung'])->name('capnhat.dangtin');
    Route::post('dangtin/capnhatdangtin/{id}',[DangtinController::class,'updatedangtin'])->name('update.dangtin');



Route::get('send-email',[\App\Http\Controllers\SendMailController::class,'sendmail']);

doantotnghiep/resources/views/admin/alert.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


@if (Session::has('error'))
    <div class="alert alert-danger">
        {{ Session::get('error') }}
    </div>
@endif


@if (Session::has('success'))
    <div class="alert alert-success">
        {{ Session::get('success') }}
    </div>
@endif

doantotnghiep/resources/views/admin/footer.blade.php
<!-- jQuery -->
<script src="../../adminlte/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../adminlte/dist/js/adminlte.min.js"></script>
<script src="public/adminlte/js/main.js"></script>
@yield('js')
@yield('footer')

doantotnghiep/resources/views/admin/head.blade.php
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{{$title}}</title>
    <meta name="csrf-token" content="{{csrf_token()}}">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../../adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../adminlte/dist/css/adminlte.min.css">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    @yield('head')

    <style>
        .hidden {
            display: none;
        }
    </style>

doantotnghiep/resources/views/admin/home.blade.php
@extends('admin.main')

@section('content')

@endsection

doantotnghiep/resources/views/admin/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('admin.head')
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">

            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->


    @include('admin.siderbar')


    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">



                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- jquery validation -->
                        <div class="card card-primary mt-3">
                            <div class="card-header">
                                <h3 class="card-title">{{ $title }}</h3>
                            </div>

                            @yield('content')

                        </div>
                        <!-- /.card -->
                    </div>
                    <!--/.col (left) -->
                    <!-- right column -->
                    <div class="col-md-6">

                    </div>
                    <!--/.col (right) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>


    <!-- /.content-wrapper -->
</div>
<!-- ./wrapper -->
@include('admin.footer')
</body>
</html>

doantotnghiep/resources/views/admin/siderbar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->


    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="{{url('http://localhost:8000/admin/profile')}}" class="d-block"><img style="width: 50px;height: 50px;border-radius: 50%" src="/upload/user/{{\Illuminate\Support\Facades\Auth::user()->Anhdaidien}}">{{\Illuminate\Support\Facades\Auth::user()->name}}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-bars"></i>
                        <p> Danh Mục Phòng Trọ
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/admin/menus/add" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p style="font-size: 14px">Thêm Danh Mục Phòng Trọ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.loaiphong')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p style="font-size: 14px">Danh Sách Loại Phòng Trọ</p>
                            </a>
                        </li>

                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-store-alt"></i>
                        <p> Quận
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{url('http://localhost:8000/admin/quan/create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Thêm Quận</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{url('http://localhost:8000/admin/quan')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Danh sách Quận</p>
                            </a>
                        </li>

                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-store-alt"></i>
                        <p> Phường
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{url('http://localhost:8000/admin/phuong/create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Thêm Phường</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{url('http://localhost:8000/admin/phuong')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Danh sách Phường</p>
                            </a>
                        </li>

                    </ul>
                </li>


                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cart-plus"></i>
                        <p>Quản lý bài đăng
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{url('/admin/dangtin')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Danh sách bài đăng</p>
                            </a>
                        </li>



                    </ul>
                </li>
                <li class="nav-item">
                    <a href="/admin/taikhoannguoidung" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>Quản lí tài khoản
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cart-plus"></i>
                        <p>Thống kê
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cart-plus"></i>
                        <p>Slide
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.logout') }}" class="nav-link">
                            <i class="ti-face-sad"></i>
                            <p class="dn">Đăng xuất</p>
                        </a>


                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>